### ISSUE TITLE
Font not loading properly

### ISSUE THREAD

**Issue by divadsn** [msfjarvis/msfjarvis.dev#13]
Despite clearing cache and even opening in Incognito, the font would not want to load, even with tracking protection disabled for testing. Looks like you forgot to load the font from Google Fonts.

![Screenshot_20200214_124100](https://user-images.githubusercontent.com/28547847/74527929-464d2080-4f27-11ea-985b-4b808f16c642.png)

**Comment by msfjarvis** [comment]
> Despite clearing cache and even opening in Incognito, the font would not want to load, even with tracking protection disabled for testing. 

I can't reproduce it on any Chrome version even after clearing all local storage and going incognito.

> Looks like you forgot to load the font from Google Fonts.

[I haven't](https://github.com/msfjarvis/msfjarvis.dev/blob/src/layouts/partials/head_fonts.html)

**Comment by divadsn** [comment]
I'm not sure if it's caused by the hacky preload stuff you did there.

pt., 14 lut 2020, 13:14 użytkownik Harsh Shandilya <notifications@github.com>
napisał:

**Comment by msfjarvis** [comment]
> I'm not sure if it's caused by the hacky preload stuff you did there.

I fail to see how a [commonly](https://www.freecodecamp.org/news/web-fonts-in-2018-f191a48367e8/) [suggested](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content) [technique](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization) for webfont performance is a hack to you. Problem's entirely on your end, my code is fine.

**Comment by divadsn** [comment]
Run it on other browsers than the monopoly shit Chrome.

pt., 14 lut 2020, 19:30 użytkownik Harsh Shandilya <notifications@github.com>
napisał:

**Comment by msfjarvis** [comment]
> Run it on other browsers than the monopoly shit Chrome.

I don't have to. Mozilla recommends the same techniques, which you'd know if you read any of the three links I sent.

**Comment by divadsn** [comment]
Didn't saw Mozilla recommending the JS hack there tho..

**Comment by divadsn** [comment]
Same on my laptop, with Firefox.

![image](https://user-images.githubusercontent.com/28547847/74589441-b4681500-5005-11ea-989f-57afbd8cd604.png)

**Comment by msfjarvis** [comment]
> Didn't saw Mozilla recommending the JS hack there tho..

What JS hack?

**Comment by divadsn** [comment]
> > Didn't saw Mozilla recommending the JS hack there tho..
> 
> What JS hack?

In the first line of the head_fonts.html it has the following code: 
`onload="this.onload=null;this.rel='stylesheet'"`

Other websites featuring preloaded fonts work fine.

**Comment by divadsn** [comment]
Maybe this gives some useful information.

![image](https://user-images.githubusercontent.com/28547847/74589551-7a4b4300-5006-11ea-9789-b52591e22453.png)

**Comment by divadsn** [comment]
On Chrome the font CSS gets loaded, as expected by you:

![image](https://user-images.githubusercontent.com/28547847/74589579-b5e60d00-5006-11ea-9d37-4a0d7f00bf75.png)
